### ISSUE TITLE
cant chroot if not mounted

### ISSUE THREAD

**Issue by rhlug** [tekcomm/AMD-rocm-rippa#2]
you never mount /mnt/root, how do you expect to chroot to it without a working shell

If you mount partition 3 first, then you can chroot and run your updates.

```
# mount /dev/sdd3 /mnt/root/
# chroot /mnt/root
```

**Comment by tekcomm** [comment]
You can either chroot by using a loop devices since its a dd image. Here is a example.
#losetup -P /dev/loop1 AMD-ROCM-RIPPA.DD 
#mount /dev/loop1p3 /mnt/sdcard/
#cd /mnt/sdcard
#mount -t proc proc proc/
#mount -t sysfs sys sys/
#mount -o bind /dev dev/
#chroot /mnt/sdcard
Your now chrooted and can modify the sdcard image directly.

**Comment by tekcomm** [comment]
Once its running here is a trick to do live backups
192.168.2.1 is your system
#nc -l 19000|bzip2 -d|dd bs=16M of=backuplive.dd

192.168.2.2 is your rig
#dd bs=16M if=/dev/sda | bzip2 -c | nc 192.168.2.1 19000
